/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        display: [
          "Space Grotesk",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        serif: [
          "Cormorant Garamond",
          "Georgia",
          "ui-serif",
          "serif",
        ],
        brush: [
          "'Zhi Mang Xing'",
          "'Ma Shan Zheng'",
          "cursive",
        ],
        hand: [
          "'Long Cang'",
          "'Zhi Mang Xing'",
          "cursive",
        ],
        script: [
          "'Caveat'",
          "'Long Cang'",
          "cursive",
        ],
      },
      colors: {
        // Mio SLOWFIRE — 高饱和·暖调窑烤色谱
        ash: "#FAF6F0",
        "ash-deep": "#F0E9E0",
        clay: "#E2D5C5",
        "clay-dark": "#C9B8A4",
        ember: "#E84A2E",
        "ember-glow": "#FF6B4D",
        "ember-dim": "#C2361A",
        kiln: "#1E1712",
        "kiln-light": "#3D3228",
        wheat: "#D4A853",
        "wheat-light": "#E8C878",
        smoke: "#7A6E62",
        "smoke-light": "#A89E94",
        ink: "#1a1a1a",
        "ink-fade": "#4a4a4a",
        seal: "#C73E1D",

        // Legacy aliases (统一指向新色值)
        flour: "#FAF6F0",
        dough: "#F0E9E0",
        crust: "#E84A2E",
        "crust-dark": "#C2361A",
        cocoa: "#1E1712",
        "cocoa-light": "#3D3228",
        stone: "#7A6E62",
        "stone-light": "#A89E94",

        // Functional
        bg: "#FAF6F0",
        fg: "#1E1712",
        muted: "#7A6E62",
        "muted-light": "#A89E94",
        accent: "#E84A2E",
        "accent-hover": "#C2361A",
        surface: "#F0E9E0",
        "surface-hover": "#E5DDD3",
        border: "#E2D5C5",
        "border-strong": "#1E1712",
        success: "#15803D",
        warning: "#D97706",
      },
      boxShadow: {
        soft: "0 1px 3px rgba(30,23,18,0.08)",
        card: "0 4px 24px rgba(30,23,18,0.06)",
        elevated: "0 12px 40px rgba(30,23,18,0.10)",
        glow: "0 0 24px rgba(232,74,46,0.12)",
        inner: "inset 0 2px 4px rgba(30,23,18,0.04)",
        "rough-sm": "2px 2px 0 rgba(30,23,18,0.08)",
        rough: "3px 3px 0 rgba(30,23,18,0.10)",
        "rough-lg": "4px 4px 0 rgba(30,23,18,0.12)",
      },
      letterSpacing: {
        tighter: "-0.03em",
        tight: "-0.02em",
        normal: "0",
        wide: "0.06em",
        wider: "0.12em",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "28px",
        rough: "255px 15px 225px 15px / 15px 225px 15px 255px",
        "rough-sm": "125px 8px 115px 8px / 8px 115px 8px 125px",
      },
      animation: {
        "fade-in": "fadeIn 0.6s ease both",
        "slide-up": "slideUp 0.5s cubic-bezier(0.22,1,0.36,1) both",
        "rise": "riseIn 0.7s cubic-bezier(0.22,1,0.36,1) both",
        "pulse-slow": "pulse 4s cubic-bezier(0.4,0,0.6,1) infinite",
        "countdown": "countdownPulse 2.5s ease-in-out infinite",
        "shimmer": "shimmer 2.5s linear infinite",
        "flicker": "flicker 3s ease-in-out infinite",
        "steam": "steam 3s ease-out infinite",
        "wiggle": "wiggle 2s ease-in-out infinite",
        "stamp": "stamp 0.4s cubic-bezier(0.22,1,0.36,1) both",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        riseIn: {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        countdownPulse: {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.04)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        flicker: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.85" },
          "75%": { opacity: "0.95" },
        },
        steam: {
          "0%": { opacity: "0", transform: "translateY(0) scale(1)" },
          "50%": { opacity: "0.6", transform: "translateY(-10px) scale(1.1)" },
          "100%": { opacity: "0", transform: "translateY(-20px) scale(1.2)" },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-1deg)" },
          "50%": { transform: "rotate(1deg)" },
        },
        stamp: {
          from: { opacity: "0", transform: "scale(1.5) rotate(-10deg)" },
          to: { opacity: "1", transform: "scale(1) rotate(-6deg)" },
        },
      },
    },
  },
  plugins: [],
};
