export const seedProducts = [
  ["lychee-rose", "荔枝玫瑰", "欧包/坚果", "280克", 35, "红酒浸润荔枝果香，玫瑰尾调清晰，适合切片分享。", ["红酒荔枝", "玫瑰", "天然酵母"], "from-rose-200 via-pink-100 to-amber-50", 1, 1],
  ["country-fruit", "乡村果实", "欧包/坚果", "280克", 32, "加州蔓越莓和热带亚麻籽，酸甜耐嚼，适合早餐。", ["蔓越莓", "亚麻籽", "乡村面团"], "from-red-100 via-orange-100 to-stone-100", 1, 0],
  ["chia-nut", "奇亚籽坚果多", "欧包/坚果", "280克", 35, "坚果香和谷物感更重，口感扎实，适合健身早餐。", ["奇亚籽", "综合坚果", "全麦粉"], "from-lime-100 via-stone-100 to-yellow-50", 1, 0],
  ["fig-goji", "无花果&枸杞子", "欧包/坚果", "280克", 35, "无花果颗粒和枸杞甜香，回烤后果香更明显。", ["无花果", "枸杞", "天然酵母"], "from-purple-100 via-orange-100 to-yellow-50", 1, 0],
  ["salt-roll", "海盐卷", "贝果/海盐卷", "70克", 11, "外壳微脆，内部柔软，黄油和海盐是主角。", ["海盐", "黄油", "高筋粉"], "from-yellow-100 via-amber-100 to-stone-50", 1, 1],
  ["cranberry-cheese-bagel", "蔓越莓乳酪贝果", "贝果/海盐卷", "85克", 15, "乳酪微咸，蔓越莓带酸甜，适合冷藏后食用。", ["乳酪", "蔓越莓", "贝果面团"], "from-rose-100 via-stone-50 to-red-50", 1, 0],
  ["orange-flower-bagel", "橙皮鲜花贝果", "贝果/海盐卷", "95克", 12, "橙皮清香和花香轻盈，适合办公室拼单。", ["糖渍橙皮", "花香酱", "贝果面团"], "from-orange-100 via-pink-50 to-yellow-50", 1, 0],
  ["pistachio-toast", "开心果吐司", "吐司", "280克", 39, "坚果脂香浓郁，整条预订更适合家庭早餐。", ["开心果", "牛奶", "吐司面团"], "from-lime-100 via-green-50 to-stone-50", 1, 1],
  ["pumpkin-toast", "贝贝南瓜吐司", "吐司", "280克", 36, "贝贝南瓜带自然甜香，口感柔软细腻。", ["贝贝南瓜", "牛奶", "吐司面团"], "from-orange-200 via-yellow-100 to-stone-50", 1, 0],
  ["coconut-toast", "奶油生椰吐司", "吐司", "280克", 36, "椰香和奶油感明显，适合作为门店主推款。", ["生椰乳", "奶油", "吐司面团"], "from-sky-50 via-stone-100 to-white", 1, 0],
  ["mushroom-cheese-ciabatta", "菌菇奶酪恰巴塔", "恰巴塔", "190克", 22, "菌菇香气和奶酪咸香，适合作为午餐轻食。", ["菌菇", "奶酪", "恰巴塔面团"], "from-stone-200 via-yellow-50 to-neutral-100", 1, 0],
  ["rose-cranberry-ciabatta", "玫瑰蔓越莓恰巴塔", "恰巴塔", "190克", 22, "玫瑰香和蔓越莓果酸平衡，适合开团试吃。", ["玫瑰", "蔓越莓", "恰巴塔面团"], "from-pink-100 via-red-50 to-stone-50", 1, 0],
  ["basil-bacon-ciabatta", "罗勒培根恰巴塔", "恰巴塔", "190克", 22, "罗勒和培根咸香明显，适合同城午间配送。", ["罗勒", "培根", "恰巴塔面团"], "from-green-100 via-amber-50 to-stone-50", 1, 0],
  ["sausage-cheese-ciabatta", "德肠芝士恰巴塔", "恰巴塔", "190克", 22, "德肠和芝士带来更强饱腹感，适合办公室拼单。", ["德肠", "芝士", "恰巴塔面团"], "from-yellow-100 via-orange-100 to-red-50", 1, 0],
  ["banana-choco-ciabatta", "香蕉巧克力恰巴塔", "恰巴塔", "190克", 22, "香蕉甜香和巧克力微苦，下午茶友好。", ["香蕉", "巧克力", "恰巴塔面团"], "from-yellow-100 via-neutral-100 to-amber-50", 1, 0],
  ["ham-mushroom-soft", "火腿菌菇软欧包", "软欧包", "120克", 20, "火腿和菌菇咸香，单人早餐或午餐都合适。", ["火腿", "菌菇", "软欧面团"], "from-amber-100 via-stone-100 to-yellow-50", 1, 0],
  ["beef-pepper-soft", "黑胡椒牛肉软欧包", "软欧包", "140克", 26, "黑胡椒香气和牛肉颗粒，适合工作日午餐。", ["牛肉", "黑胡椒", "软欧面团"], "from-stone-300 via-red-100 to-amber-50", 1, 0],
  ["brownie-soft", "布朗尼软欧包", "软欧包", "180克", 26, "巧克力甜点型软欧，适合加购和分享。", ["布朗尼", "巧克力", "软欧面团"], "from-neutral-300 via-amber-100 to-stone-100", 1, 0],
];

export const seedStores = [
  ["store-a", "A 店 · 中央厨房", "central", "中央厨房与主门店", 1, "MIO-A"],
  ["store-b", "B 店 · 社区自提点", "pickup", "社区北门自提点", 1, "MIO-B"],
  ["store-c", "C 店 · 商圈自提点", "pickup", "商圈咖啡店联名点", 1, "MIO-C"],
  ["store-d", "D 店 · 写字楼自提点", "pickup", "写字楼前台自提", 1, "MIO-D"],
];

export const seedBatchSale = {
  id: "current",
  isOpen: 1,
  deadline: "今晚 21:30",
  ovenBatch: "明日 10:30 / 16:30 出炉",
  featuredProductIds: ["lychee-rose", "salt-roll", "pistachio-toast"],
  pickupStoreIds: ["store-a", "store-b", "store-c", "store-d"],
  freeShippingThreshold: 150,
  baseShippingFee: 10,
  note: "集中预订，按门店分配库存，次日到店自提或本地配送。",
};

export const seedOrders = [
  {
    id: "MIO2601",
    type: "online",
    items: [
      { productId: "lychee-rose", name: "荔枝玫瑰", qty: 2, price: 35 },
      { productId: "salt-roll", name: "海盐卷", qty: 5, price: 11 },
    ],
    subtotal: 125,
    shippingFee: 0,
    total: 125,
    deliveryMethod: "门店自提",
    paymentMethod: "微信支付",
    status: "待生产",
    sourceStoreId: "store-b",
    pickupStoreId: "store-b",
    pickupCode: "482913",
    createdAt: "09:42",
  },
  {
    id: "MIO2602",
    type: "online",
    items: [{ productId: "pistachio-toast", name: "开心果吐司", qty: 4, price: 39 }],
    subtotal: 156,
    shippingFee: 0,
    total: 156,
    deliveryMethod: "顺丰快递",
    paymentMethod: "支付宝",
    status: "待发货",
    sourceStoreId: "store-c",
    pickupStoreId: "store-c",
    receiver: "王女士",
    phone: "138****2031",
    address: "上海市徐汇区某小区",
    pickupCode: "705318",
    createdAt: "10:16",
  },
  {
    id: "POS0816",
    type: "pos",
    items: [
      { productId: "salt-roll", name: "海盐卷", qty: 2, price: 11 },
      { productId: "brownie-soft", name: "布朗尼软欧包", qty: 1, price: 26 },
    ],
    subtotal: 48,
    shippingFee: 0,
    total: 48,
    deliveryMethod: "门店自提",
    paymentMethod: "现金",
    status: "已完成",
    sourceStoreId: "store-a",
    pickupStoreId: "store-a",
    pickupCode: "116820",
    createdAt: "11:05",
  },
];
